dist: trusty
language: rust
cache: cargo

env: TARGET=arm-unknown-linux-gnueabihf CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: kWPhjBz7v38yaNvqLiVJiqFM8Y/mzNk3IyGDJ7qs9Dn2BlwcFIBGi5aNNaMLBFZHdUrg3/C5nt8rjAb/c+XTGAeDmcL2zGuedkcRbt0u9sVN75brsHXTELr8bABJ0cO5UzJZJpMeNF+RK+U4KWRkajASkFmqTSxZ9IJShGJw83mJd3evVZHP1tgJ1RlzG5n3dzb5+6z89AaHV3wAZyJt95WLlC4mJ3WTCmnMEfRcCUw7dY1W7SvKKVHtCO9EPGB1fufQwX5ceYABg3TG0e/QZkOWvwGPKmGGnPNQ+W9O5TZPTievVQKf7mbywAJFqhSzMs/88pZG3EkzYu6R0SgD3VoPM0RBSm9AWgZ3lYM4M6/iwOjIHfv44egJX7mljnNEBADTr45PBMbyCvCcFbPiQIqFVWlM6KHF/xujnl3aQ3hRIrnlaNDTvYM5ZbCAnFPL/FwXySqeGQus7bGsWxSUL6RPjVYmDCg1quyc7OkuFZrne0bSoa2mrw2KeHsn/8R1zVZ70fktjs1qmRurO/wX5lgeK2ktjXtgxyAhlpbZKlfl3OFucz0hfgmIviQbX2qjUslnfnUuVQXznetFx4ec5rwLa9Bjk+Klt7NhXwApjInimuPnw7wBkTN3pmyN1+Po0ze12Of3J8XBSa1fW4GkwhD2dEDfLmydlPTUEye8Hg8=
  file: target/**/*.deb
  on:
    repo: Dalvany/rparif-influxdb
    tags: 'true'
  skip_cleanup: 'true'