dist: trusty
language: rust
cache: cargo

env: TARGET=arm-unknown-linux-gnueabihf CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: tAi/hKhliPwZJoL1QRxo2Z8pHEOj4JGrjM3sNei4OHUDZxv0+DJa52lRzEPvqtwy/b2nyzrzVA+/ZChKPfJpdZCqOTTOPpRYLjFHe45fKvJMw07NZP/N19faPKB5Zy+CG14UeNAthtzYYDQ9lfwI0ooJjQYkPRuXjnrofSOGw7rgZeAYXt+j7JajKIWexmjSpq60qq9IeHo6KuflGI+dVEW93yuF+4/x1mtNR60zWPEhM0kjuLaRXM5lSrl+57ggNqYbiawW+ruQMWdx4WzpU+7doRL6j1lG/VuW+hcrV5rgY5TmRIhw753CBNZGHlc3vnZQNvZLpnbwI9LUhoKB4KNAYlcAarZHWhcoJoAtUyGR8DTKe7D1D5hlrMfcLmFMd081t8QjtmiQWX4kfetwy9QfL/zyWQVS5UY/nXT/fK37gcC/jLxnlY79RwkfLwxyN8gKfrv+GDNCJVGdaefQ9gKQ5YQ++2z8dY+/RoW8sxjeYYI2Y86kRyueDW7C3R0k08yqXd7nL77+EK5xguRKJxAm4YEHfH5AqIGWQa1wtKErhraD5RC2NiIuNkpmPM444KxEkNZFnl1tR8TWTeCRGncXQdD0Eff+EkoCwPRX31wHb30eB+H8xBtgNTrLQbblm8eeqlv9hh450hBEqpLDZhWEx+VSocrJgvPOPu1OWkY=
  file: target/**/*_armhf.deb
  on:
    tags: true
  skip_cleanup: true